services:
  backend:
    build:
      context: ./backend
    container_name: ai-backend
    ports:
      - "3001:3001"
    env_file:
      - ./backend/.env
    networks:
      - ai_net
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
    container_name: ai-frontend
    ports:
      - "3000:3000"
    env_file:
      - ./frontend/.env
    depends_on:
      - backend
    networks:
      - ai_net
    restart: unless-stopped

networks:
  ai_net:
    driver: bridge
