---
name: CI Pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      NEXT_PUBLIC_SUPABASE_URL: https://example.supabase.co
      NEXT_PUBLIC_SUPABASE_ANON_KEY: dummy-key

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: |
          cd backend && npm install
          cd ../frontend && npm install

      - name: Build Frontend
        run: |
          cd frontend && npm run build --no-lint

      - name: Test Backend Startup
        run: |
          cd backend && node src/index.js &
          sleep 5
          curl -f http://localhost:3001 || exit 1

      - name: Lint Backend
        run: |
          cd backend
          npx eslint src --ext .js

      - name: Run Backend Tests
        run: |
          cd backend
          npx jest --passWithNoTests
