---
name: CI Pipeline

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: |
          cd backend && npm ci
          cd ../frontend && npm ci || echo "Frontend skipped if submodule"

      - name: Build Frontend (skip if submodule)
        run: |
          if [ -d "frontend" ] && [ -f "frontend/package.json" ]; then
            cd frontend && npm run build --no-lint
          else
            echo "No frontend folder detected, skipping build."
          fi

      - name: Test Backend Startup
        run: |
          cd backend && node src/index.js &
          sleep 5
          curl -f http://localhost:3001 || exit 1

